name: Build-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build-unit-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install NPM packages
        run: npm install
      - name: Run Unit tests
        run: npm run test:unit

  build-UI-tests:
    needs: build-unit-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install NPM packages
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Start application
        run: npm run start &
      - name: Run Unit tests
        run: npm run test:ui
      - name: Display your softuni username
        run: echo "vidrax"
